apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cloudflare.name }}
  namespace: cert-manager
spec:
  acme:
    email: {{ .Values.cloudflare.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflare.email }}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
