{{ if not .Values.external_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
  {{- include "wosp.labels" . | nindent 4 }}
type: Opaque
data:
  SIGNING_KEY: {{ .Values.backend.signing_key | b64enc | quote }}
{{ end }}