{{ if not .Values.external_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
  {{- include "wosp.labels" . | nindent 4 }}
type: Opaque
data:
    DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
{{ end }}