apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
  {{- include "wosp.labels" . | nindent 4 }}
data:
  DB_DATABASE: {{ .Values.wosp.db.database | quote }}
  DB_HOST: {{ .Values.wosp.db.hostname | quote }}
  DB_USERNAME: {{ .Values.wosp.db.username | quote }}