version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-wosp}
      POSTGRES_USER: ${DB_USER:-wosp}
      POSTGRES_DB: ${DB_NAME:-wosp}
    ports:
      - 5432:5432

  backend:
    image: nofrostoo/todo-app:dev
    environment:
      Signing_Key: ${SIGNING_KEY:-secret}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_URL}`)"
      - "traefik.http.middlewares.frontend-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.frontend-https.redirectscheme.permament=true"
      - "traefik.http.routers.backend-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-secure.rule=Host(`${BACKEND_URL}`)"
      - "traefik.http.routers.backend-secure.tls.certResolver=myresolver"
      - "traefik.http.services.backend-secure.loadbalancer.server.port=8080"
    depends_on:
     - db  
  
  frontend:
    image: nofrostoo/todo-app-frontend:dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_URL}`)"
      - "traefik.http.routers.frontend.middlewares=frontend-https"
      - "traefik.http.middlewares.frontend-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.frontend-https.redirectscheme.permament=true"
      - "traefik.http.routers.frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-secure.rule=Host(`${FRONTEND_URL}`)"
      - "traefik.http.routers.backend-secure.tls.certResolver=myresolver"
      - "traefik.http.services.frontend-secure.loadbalancer.server.port=80"
  
  traefik:
    image: "traefik:v3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=daniel.lipniacki@proton.me"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
