version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: wosp
      POSTGRES_USER: wosp
      POSTGRES_DB: wosp
    ports:
      - 5432:5432

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      Signing_Key: "secret"
      DB_PASSWORD: wosp
      DB_USERNAME: wosp
      DB_NAME: wosp
      DB_HOST: db
    ports:
      - 8080:8080
    depends_on:
     - db  
  
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80
      - 8082:443
  
  
