apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
  {{- include "wosp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: backend-http
  selector:
    name: backend