apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
  {{- include "wosp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: database
  selector:
    name: database