apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
  {{- include "wosp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: frontend-http
  selector:
    name: frontend