# Default values for wosp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

external_secrets:
  enabled: false
  class_name: ""
  secret_name: ""

image:
  repository: nofrostoo
  tags:
    backend: dev
    frontend: dev


ingress:
  enabled: false
  className: ""
  domain: "piwo.pw"
  tls:
    secretName: ingress-tls-secret
    hosts:
      - piwo.pw

db:
  password: "wosp"
  username: "wosp"
  database: "wosp"
  hostname: "database"

backend:
  signing_key: "xadaRFAFAFASFAFAFAF"


replicas:
  backend: 1