---
name: Build and Run

on:
  push:
    branches:
      - main
      - docker-build-ci

jobs:
  build-backend:
    if: ${{ contains(github.event_name, 'push') && contains(github.event.head_commit.modified, 'backend/') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Backend
      run: |
       pwd
       ./build-backend-push.sh
      shell: bash
      
  build-frontend:
    if: ${{ contains(github.event_name, 'push') && contains(github.event.head_commit.modified, 'frontend/') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Frontend
      run: |
        pwd
        ./build-frontend-push.sh
      shell: bash
