---
name: Build frontend image on change

on:
  push:
    branches:
      - main
      - docker-build-ci
    paths:
      - frontend/**

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Frontend
      env:
        DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
       docker login --username "$DOCKER_HUB_LOGIN" --password "$DOCKER_HUB_TOKEN"
       ./scripts/build-frontend-push.sh
      shell: bash


docker login --username nofrostoo --password dckr_pat_4EAdN-i2IZW8rq7k78apzHyK3tc
