---
name: Test backend code

on:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Go 
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - name: Test code
      run: |
       cd backend
       go test ./...
      shell: bash